version: '3.1'
services:
    jenkins:
        build: ./jenkins/master
        image: satixfy-repo.devopshift.com/jenkins-master:1.0
        container_name: jenkins
        ports:
            - '8080:8080'
            # - '50000:50000'
        networks: 
            - jb
    jenkins-slave:
        build: ./jenkins/slave
        image: satixfy-repo.devopshift.com/jenkins-slave:1.0
        # Removed container name to support scale out option 
        #container_name: jenkins-slave 
        restart: always
        environment:
            - 'JENKINS_URL=http://jenkins:8080/jenkins/'
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock  # Expose the docker daemon in the container
            - ./volume:/home/jenkins # Avoid mysql volume mount issue
        networks: 
        - jb
        depends_on:
            - jenkins
        
    nginx:
      image: nginx:1.25.3-alpine
      restart: unless-stopped
      hostname: satixfy-repo.devopshift.com
      volumes:
        - ./jenkins/nginx/conf/nginx-cicd.conf:/etc/nginx/conf.d/nginx-cicd.conf
        - ./jenkins/nginx/letsencrypt/archive/satixfy-repo.devopshift.com/:/etc/certificates
      ports:
        - "80:80"
        - "443:443"
        - "5001:5000"
      command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
      # entrypoint: "sleep 60000"
      depends_on:
        - jenkins
        - nexus
      networks:
        - jb
    
  #   sonarqube:
  #       image: sonarqube
  #       restart: unless-stopped
  #       ports:
  #         - 0.0.0.0:9000:9000
  #         - 0.0.0.0:9092:9092
  #       networks:
  #        - nexus
    nexus:
          image: sonatype/nexus3
          restart: unless-stopped
          volumes: 
            - ./volume/nexus/data:/nexus-data
          environment:
            - NEXUS_CONTEXT=nexus
          user: root
          networks:
          - jb


networks: 
  jb:

volumes:
  nexus-data:
  