server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: flog_scrape
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: label
            values: ["logging=promtail"]
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'logstream'
      - source_labels: ['__meta_docker_container_label_logging_jobname']
        target_label: 'job'
  - job_name: dataLogs
    static_configs:
      - targets:
          - localhost
        labels:
          job: dataLogs
          __path__: /var/log/targetlogsflat.txt
    pipeline_stages:
      - json:
          expressions:
            date: "date"
            type: "type"
            service: "service"
            class: "class"
            SessionID: "SessionID"
            message_transactionid: "message_transactionid"
            message_rentCustomerId: "message_rentCustomerId"
            message_firstName: "message_firstName"
            message_lastName: "message_lastName"
            message_governmentId: "message_governmentId"
            message_telephone1: "message_telephone1"
            message_telephone2: "message_telephone2"
      - labels:
          SessionID: 
          type: 
          service: 
          class: 
      - output:
          source: message