# For testing: 
# Linux:
#BUILD_NUMBER=1.0.0 Dockerfile_Name=Dockerfile NEXUS_API_KEY=121d0000-0f4c-314a-8674-ca3f2db5847a docker-compose build
# Windows Powershell 
# $env:BUILD_NUMBER = "1.0.0"
# $env:Dockerfile_Name = "DockerfileWindows"
# $env:NEXUS_API_KEY = "121d0000-0f4c-314a-8674-ca3f2db5847a"
# $env:BRANCH="master"
# docker-compose --parallel 1 build --build-arg NEXUS_API_KEY=$env:NEXUS_API_KEY --build-arg BUILD_NUMBER=$env:BUILD_NUMBER  --build-arg BRANCH=$env:BRANCH


services:
  # test:
  #   build:
  #     context: './src/test'
  #     dockerfile: ${Dockerfile_Name}
  #     args:
  #       - NEXUS_API_KEY=${NEXUS_API_KEY}
  #       - BUILD_NUMBER=${BUILD_NUMBER}
  #   image: eldan/image-processing:${BUILD_NUMBER}
  
  ImageProcessing:
    build:
      context: './src/ImageProcessing/real/ImageProcessing'
      dockerfile: ${Dockerfile_Name}
      args:
        - NEXUS_API_KEY=${NEXUS_API_KEY}
        - BUILD_NUMBER=${BUILD_NUMBER}-${GIT_BRANCH}
    image: eldan/image-processing:${BUILD_NUMBER}-${GIT_BRANCH}

  SecurityBase:
    build:
      context: './src/SecurityBase/real/SecurityBase'
      dockerfile: ${Dockerfile_Name}
      args:
        - NEXUS_API_KEY=${NEXUS_API_KEY}
        - BUILD_NUMBER=${BUILD_NUMBER}-${BRANCH}
    image: eldan/security-base:${BUILD_NUMBER}-${BRANCH}

  ServicesSchedulerLib:
    build:
      context: './src/ServicesSchedulerLib/real/ServicesSchedulerLib'
      dockerfile: ${Dockerfile_Name}
      args:
        - NEXUS_API_KEY=${NEXUS_API_KEY}
        - BUILD_NUMBER=${BUILD_NUMBER}-${BRANCH}
    image: eldan/services-scheduler-lib:${BUILD_NUMBER}-${BRANCH}

  SharedTypes:
    build:
      context: './src/SharedTypes/real/SharedTypes'
      dockerfile: ${Dockerfile_Name}
      args:
        - NEXUS_API_KEY=${NEXUS_API_KEY}
        - BUILD_NUMBER=${BUILD_NUMBER}-${BRANCH}
    image: eldan/shared-types:${BUILD_NUMBER}-${BRANCH}

  TypeExtensions:
    build:
      context: './src/TypeExtensions/real/TypeExtensions'
      dockerfile: ${Dockerfile_Name}
      args:
        - NEXUS_API_KEY=${NEXUS_API_KEY}
        - BUILD_NUMBER=${BUILD_NUMBER}-${BRANCH}
    image: eldan/type-extensions:${BUILD_NUMBER}-${BRANCH}

  SSOlogon:
    build:
      context: './src/SSOlogon/real/SSOlogon'
      dockerfile: ${Dockerfile_Name}
      args:
        - NEXUS_API_KEY=${NEXUS_API_KEY}
        - BUILD_NUMBER=${BUILD_NUMBER}-${BRANCH}
    image: eldan/sso-logon:${BUILD_NUMBER}-${BRANCH}

  QR:
      build:
        context: './src/QR/real/QR'
        dockerfile: ${Dockerfile_Name}
        args:
          - NEXUS_API_KEY=${NEXUS_API_KEY}
          - BUILD_NUMBER=${BUILD_NUMBER}-${BRANCH}
      image: eldan/qr:${BUILD_NUMBER}-${BRANCH}

  FireflyBox:
    build:
      context: './src/FireflyBox'
      dockerfile: ${Dockerfile_Name}
      args:
        - NEXUS_API_KEY=${NEXUS_API_KEY}
        - BUILD_NUMBER=${BUILD_NUMBER}-${BRANCH}
    image: eldan/firefly-box:${BUILD_NUMBER}
